name: Java CI with Gradle (3 OS)

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
	java: [21]
    runs-on: ${{ matrix.os }}

    steps:
      - uses: actions/checkout@v4

      - name: Set up JDK ${{ matrix.java }}
        uses: actions/setup-java@v4
	with:
	  java-version: ${{ matrix.java }}
	  distribution: temurin
	  cache: gradle

     - name: Ensure gradlew is executable (Unix)
       if: runner.os != 'Windows'
       run: chmod +x gradlew

     - name: Build with Gradle (Unix)
       if: runner.os != 'Windows'
       run: ./gradlew build

     - name: Build with Gradlew (Windows)
       if: runner.os == 'Windows'
       run: gradlew build