name: Java CI with Gradle (3 OS)

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
        java: [21]

    steps:
      - uses: actions/checkout@v4

      - name: Set up JDK ${{ matrix.java }}
        uses: actions/setup-java@v4
        with:
          java-version: ${{ matrix.java }}
          distribution: temurin
          cache: gradle

      # Show where we are + prove the wrapper files exist
      - name: Show wrapper files
        run: |
          pwd || cd
          ls -la
          ls -la gradle || true
          ls -la gradle/wrapper || true

      # Unix (Linux/macOS)
      - name: Ensure gradlew is executable (Unix)
        if: runner.os != 'Windows'
        run: chmod +x gradlew

      - name: Build with Gradle (Unix)
        if: runner.os != 'Windows'
        run: |
          ./gradlew --version
          ./gradlew build --no-daemon --stacktrace

      - name: Build with Gradle (Windows)
        if: runner.os == 'Windows'
        shell: pwsh
        run: |
          Get-ChildItem -Force
          Get-ChildItem gradle/wrapper -Force
          .\gradlew.bat --version
          .\gradlew.bat build --no-daemon --stacktrace

